---
- name: Apache Basic insstallation
  hosts: web
  become: yes
  task: 
    - name: Install apache
      yum:
	    name: httpd
	    state: present
	- name: start apache
      service:
	    name: httpd
	    state: stopped
